spring:
  application:
    name: 3ddd_developer
  profiles:
    active:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:3ddd_developer;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: 3dddadmin
    keyStoreType: PKCS12
    keyAlias: bns-ssl


3ddd:
  mail:
    address: 3ddd.developers@gmail.com
    password: 3ddd_admin



